[build]
rustdoc = "/home/melker/.local/lib/kache/shims/rustdoc"
rustc-wrapper = "kache"
jobs = 20 # number of parallel jobs

[env]
HOST_CC = "kache cc"
HOST_CXX = "kache c++"
CC_KNOWN_WRAPPER_CUSTOM = "kache"
