# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-465ae7a9-98cc-402d-a7b6-3f35ae56e8f2";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-465ae7a9-98cc-402d-a7b6-3f35ae56e8f2".device =
    "/dev/disk/by-uuid/465ae7a9-98cc-402d-a7b6-3f35ae56e8f2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/C23A-D645";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # Hibernation (https://nixos.wiki/wiki/Hibernation)
  boot.kernelParams = [ "resume_offset=195610624" ];
  boot.resumeDevice = "/dev/disk/by-uuid/8981ed1d-50a3-4aa3-a8c3-4594006fa0a1";
  powerManagement.enable = true;
  swapDevices = [{
    device = "/var/lib/swapfile";
    size = 32 * 1024; # 32 GB
  }];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
